title: <p align="center"> Peggy Lee </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/chriskhanhtran/">LinkedIn</a> |
  <a href="https://github.com/chriskhanhtran">GitHub</a>
  </p>
  
  <p align="justify">
  I achieve an MS degree in Information Science at the School of Information, University of Arizona.
  <br><br>
  My goal is to conceptualizating of medical science, artiﬁcial intelligence, software engineering, and information technology.
  <br><br>
  </p>
  
google_analytics: UA-145578661-1 # Google Analytics tracking ID
